### ISSUE TITLE
input 和 input group 在 invalid 情况下 hover 的效果不一致

### ISSUE THREAD

**Issue by mario-mui** [alauda/alauda-ui#60]
input invalid 的hover 效果如下图
![image](https://user-images.githubusercontent.com/7720722/98094312-12a29400-1ec4-11eb-972f-e44cba83478d.png)

input group 在 invalid 情况下的 hover 效果
![image](https://user-images.githubusercontent.com/7720722/98094376-2b12ae80-1ec4-11eb-8de1-cb17cbb22e67.png)

**Comment by JounQin** [comment]
close in favor of #77
