### ISSUE TITLE
Tags input加校验

### ISSUE THREAD

**Issue by zangguodong** [alauda/alauda-ui#68]
现有问题：
目前aui-tags-input无法支持对输入数据进行校验，判断是否有效后再插入。导致的问题就是，如果输入不合法的数据，必须在tag生成后，删除，这既有一个闪动的效果，也无法很好的展示错误原因（只能拉一个notificationService），而且用户也不好调整错误数据
实现目标效果：
![image](https://user-images.githubusercontent.com/29418459/101733155-5c9d1c00-3af9-11eb-9dd1-88d1ad04de8c.png)

实现难点：
由于aui-tags-input本身作为ControlValueAccessor，暴露给FormControl，NgModel等指令的数据是生成后的数组形式，也就是说，FormControl，NgModel等的所有相关校验器，无论是在模板上指令添加：[pattern]='xxx'，或ts添加: this.fb.control('',Validator.requried)，都应该是针对数组形式的数据。问题是，数组所展示的数据，是在输入已经完成后，再插入到数组中的，此时想对输入数据做校验，已经太晚了。

实现思路：
保留用户对aui-tags-input数组形式数据的校验器，对于输入数据的校验，会提供单独的输入变量。两个输入分别为
inputValidatorFn，inputAsyncValidatorFn
来分别解决对输入数据的校验与异步校验的问题
可传入单个校验器，或者数组校验器，实现时会将数组形式的多个校验器合并。这些校验器会传递给一个内置的FormControl变量，在每次将要生成tag时，先根据输入的value，对该内部FormControl进行校验，判断是否应该生成，以及什么时候生成tag。如果校验为invalid，会给外层的 NgControl setError一个 {inputError: {...}}，来确保不与 aui-tags-input 自身的error冲突

**Comment by JounQin** [comment]
PR 应该关联一下这个 issue 的

close in favor of #69
